name: Publish to Central Repository

on:
  workflow_dispatch:
  release:
    types: [created]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - run: |
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - run: mvn -B -ntp deploy -P gpg -Dgpg.passphrase=${{ secrets.GPG_SECRET_PASS }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_NAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASS }}
